### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gustahthorres** [ParadoxLabs-Inc/tokenbase#4] opened 2023-09-13 03:04 UTC
# :bug: Bug report

## Current Behavior

I am having a problem entering an order and clicking on "Get Payment Update", as I am receiving an error from the "ParadoxLabs/TokenBase" module

Error: Call to a member function setAdditionalInformation() on bool in /var/www/vhosts/domain.com/httpdocs/app/code/ParadoxLabs/TokenBase/Model/AbstractMethod.php:749

## Expected Behavior

What I hope is that when I enter an order and click "Get Payment Update", it doesn't give me any Paradox errors and allows me to continue.

## Minimal reproduction of the problem with instructions

Go to Magento Admin -> Sales -> Order -> Select any order paid by "paradox" -> click to "Get Payment Update"

## Environment

<pre><code>
TokenBase version: 4.1.0
Magento version: 2.4.5
PHP version: 8.1.2

Others:

</code></pre>

**Comment by rhoerr** [comment] 2023-09-13 17:55
Thanks for reporting this! It looks like this will happen if there is no open authorization transaction on the order. Could you give a screenshot of the 'Transactions' tab on the admin order view? (Without any identifying info)

That will help us confirm the cause.

Do you have the payment method configured to capture at checkout?

**Comment by gustahthorres** [comment] 2023-09-15 13:51
Hello, I already solved the error.

The error was that a transaction was not recorded in that order.

Thank you anyway.

**Comment by rhoerr** [comment] 2023-09-15 14:08
Okay, thank you @gustahthorres. Just to confirm, was the issue that caused that unrecorded transaction something outside our payment modules?

I think I'll still make a code change to prevent this PHP error under these particular circumstances.

**Comment by rhoerr** [comment] 2023-10-26 14:24
Fixed in cfacd29cb50979ad0a74a3aca7b197c31112774c

**Closed as completed by rhoerr** 2023-10-26 14:24 UTC
Labels: bug
